### PR TITLE
Deprecate pin_to_date, add pin_date

### PR DESCRIPTION
**Pull request by pitkant**

### CODE REVIEW

**Comment by MansMeg** [comment]
Some checks fail. Mainly that pin_to_date miss documentation and deprecated warnings in examples.

I think the documentation can be fixed with @rdname pin_date for pin_to_date and chabgibg to pin_date in the examples.

**Review by MansMeg — COMMENTED** [review]
Thats great! Now only the coveralls complain. Could you add just one test that pin_to_date() should throw a warning about being deprecated, and still return a correct date. Ie just copy a test from pin_date() but with expect_warning() instead of expect_silent(). We should have tests also for deprecated functions.

**Comment by pitkant** [comment]
Thanks for reviewing. I was unsure about testing deprecated functions but now it should be sufficient. I also added a couple of new tests for added test coverage.

**Comment by MansMeg** [comment]
Great! Thanks!

**Pull request merged**
